name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: aactions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
          cd frontend
          npm i
          npm run build
