# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_validate_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Executar Testes
      run: npm test

    - name: Validar Conventional Commits
      run: npm run validate-commits  # caso tenha um script para validar os commits

    - name: Geração Automática de Versões
      run: npm run semantic-release  # caso tenha uma configuração para o semantic-release

    - name: Build do Aplicativo
      run: npm run build
